### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by mdisec** [cagdasc/cobot#4]
I'm getting following error.

```
Traceback (most recent call last):
  File "colyzer/main.py", line 58, in <module>
    crawler = Crawler(settings)
  File "/Users/mince/.pyenv/versions/2.7.10/lib/python2.7/site-packages/scrapy/crawler.py", line 32, in __init__
    self.spidercls.update_settings(self.settings)
AttributeError: 'Settings' object has no attribute 'update_settings'
```

**Comment by Thibaut-Fatus** [comment]
Same here
